src/assets/css/pred_fonts_styles.css

Se corrige archivo CSS

---

Tienda-Producto.html

Enlace de tienda-producto a las otras secciones.

Enlace de tienda-producto a las otras secciones

---

contacto.html

se agregaron los enlaces a la pagina

Se agregaron los enlaces

---

tienda.html

Se modificaron las referencias de GameJoy, más productos, contactos, Login, Preguntas frecuentes.

Se modificaron las referencias del footer

---

Tienda-Producto.html

Correcion de texto

---

acerca-de-nosotros.html

Se modifico /src

---

index.html

se corrige index

---

tienda.html

Quité las diagonales antes del "src" para que se vean las imágenes del footer

Arreglé las imágenes en tienda.html

---

acerca-de-nosotros.html

Se actualizaron vinculos Footer

Se actualizaron vinculos footer

---

src/assets/css/usuario-perfil-styles/usuario-perfil-styles.css
usuario-perfil.html

Se agregan cambios de usuario-perfil.html, y estilos asociados con base a los acuerdos de la junta del 7/2/2022

Se agregan cambios de la junta 2/7/2022

---

index.html
src/assets/css/inicio-styles/inicio-styles.css

Se hiso cambio de barra de navegación, cambio del borde de los productos mas vendidos y cambio del logo de la pagina de inicio.

Subiendo cambios de Home

---

registrate.html
src/assets/css/registro-styles/registro.css
src/assets/js/registro-js/formulario-registro.js

Cambios en la página regístrate

nuevos cambios en registrate

---

src/assets/js/registro-js/formulario-registro.js

Cambios en la página regístrate

formulario registro en buen estado

---

src/assets/css/preguntas-frecuentes-style/preguntas-frecuentes.css

cambios de botones

---

tienda.html

Se agrego al menú un sub menú despegable en el apartado de tienda. Únicamente en la pagina de Tienda.html. Agregar esas líneas a las otras paginas html. 
También se cambio el margen de los botones lanzamientos y playstion por color de margen azul y rojo.

Se agrego el sub menú al apartado de tienda en el nav

---

tienda-accesorios.html

Subiendo tienda-accesorios

---

tienda-xbox.html

play station

---

preguntas.frecuentes.html

nuevos cambios preguntas

---

contacto.html
iniciar-sesion.html
registrate.html
src/assets/css/iniciar-sesion-styles/iniciar-sesion.css
src/assets/css/registro-styles/registro.css

diseño responsive registrate

---

iniciar-sesion.html
registrate.html
src/assets/css/iniciar-sesion-styles/iniciar-sesion.css
src/assets/css/registro-styles/registro.css

responsive arreglado

---

iniciar-sesion.html
preguntas.frecuentes.html

Cambios de las páginas preguntas y los responsivos

responsivo y titulo arreglado

---

src/assets/css/registro-styles/registro.css

pequeño error resuelto

---

iniciar-sesion.html
registrate.html
src/assets/css/iniciar-sesion-styles/iniciar-sesion.css
src/assets/css/registro-styles/registro.css

nuevos cambios responsivos

---

index.html

Subiendo los cambios de minusculas a mayusculas

Subiendo los cambios de minusculas a mayusculas

---

src/assets/css/carrito/carrito.css
src/assets/css/contacto-styles/contacto-styles.css
src/assets/css/iniciar-sesion-styles/iniciar-sesion.css
src/assets/css/inicio-styles/inicio-styles.css
src/assets/css/pred_fonts_styles.css
src/assets/css/registro-styles/registro.css
src/assets/css/sobre-nosotros-styles/acerca-de-nosotros-styles.css
src/assets/css/tienda-styles/tienda.css

Se hizo responsive el sub menú

Se hizo responsive el sub menú

---

src/assets/css/iniciar-sesion-styles/iniciar-sesion.css
src/assets/css/registro-styles/registro.css

nuevos cambios

---

src/assets/css/registro-styles/registro.css

cambios para ser responsivo

---

base_datos/Creacion de Tablas.sql
base_datos/Ingresar Compras.sql
base_datos/Ingresar Productos.sql
base_datos/Ingresar Usuarios.sql
src/assets/css/tienda-productos-styles/tienda-producto-styles.css
src/assets/js/carrito/carrito.js
src/assets/js/productos-js/boton_carrito.js
src/assets/js/productos-js/tienda-Ofertas.js
src/assets/js/productos-js/tienda-accesorios.js
src/assets/js/productos-js/tienda-lanzamentos.js
src/assets/js/productos-js/tienda-nintendo.js
src/assets/js/productos-js/tienda-playstation.js
src/assets/js/productos-js/tienda-xbox.js
tienda-accesorios.html
tienda-lanzamientos.html
tienda-nintendo.html
tienda-ofertas.html
tienda-playstation.html

Tienda Productos
